apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: la2da-git-clone
  labels:
    owner: la2da
    app: tekton
spec:
  params:
    - description: Name of application to deploy in openshift
      name: project
      type: string
    - description: Url of git repository with project code
      name: git-url
      type: string
  steps:
    - image: registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:a652e2fec41694745977d385c845244db3819acca926d85a52c77515f1f2e612
      name: git-clone
      resources: {}
      script: >
        PROJECT=$(params.project)
        URL=$(params.git-url)
        GIT_USER=$(cat $(workspaces.secret.path)/GIT_USER)
        GIT_PASS=$(cat $(workspaces.secret.path)/GIT_PASS)
        BRANCH=develop

        rm -fr $PROJECT

        URL_WITH_CREDENTIALS="https://"${GIT_USER}:${GIT_PASS}@${URL#"https://"}

        echo "git clone -b $BRANCH $URL_WITH_CREDENTIALS $PROJECT"
        git clone -b $BRANCH $URL_WITH_CREDENTIALS $PROJECT

        echo "Making file with git credentials"
        cat <<EOF > .git/config
          [remote "origin"]
            url = $URL_WITH_CREDENTIALS
        EOF

      workingDir: $(workspaces.workspace.path)
  workspaces:
    - description: Workspace to clone and work in the project
      name: workspace
    - description: Secret with all credententials needed
      name: secret
