apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: la2da-git-tag
  labels:
    owner: la2da
    app: tekton
spec:
  params:
    - description: Name of application to deploy in openshift
      name: project
      type: string
  steps:
    - image: registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:a652e2fec41694745977d385c845244db3819acca926d85a52c77515f1f2e612
      name: git-tag
      resources: {}
      script: >
        PROJECT=$(params.project)

        cd $PROJECT

        echo "Making new version tag"
        ACTUAL_VERSION=$(grep -oPm1 "(?<=<version>)[^<]+" pom.xml)

        MAYOR="$(echo $ACTUAL_VERSION | cut -d'.' -f1)"
        MINOR="$(echo $ACTUAL_VERSION | cut -d'.' -f2)"
        PATCH="$(echo $ACTUAL_VERSION | cut -d'.' -f3)"

        NEW_VERSION=$MAYOR.$((MINOR + 1)).$PATCH
        echo "From $ACTUAL_VERSION to $NEW_VERSION"

        echo "Changing new version in POM"
        sed -i "s/<version>$ACTUAL_VERSION/<version>$NEW_VERSION/g" pom.xml

        echo "Pushing new version tag"
        git add .
        git commit -m "New version $NEW_VERSION"
        git push origin
        git tag $NEW_VERSION
        git push origin --tags

      workingDir: $(workspaces.workspace.path)
  workspaces:
    - description: Workspace to clone and work in the project
      name: workspace
    - description: Secret with all credententials needed
      name: secret
