apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: prueba-listener
  namespace: tekton
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: prueba-binding
      name: prueba-trigger
      template:
        ref: prueba-template
